services:
  _defaults:
    autowire: true
    autoconfigure: true
  #ICS\WebapiBundle\Controller\:
  #resource: "../src/Controller"
  #tags: ['controller.services_arguments']
  #ICS\WebapiBundle\Service\:
  #resource: "../src/Service"
  #tags: ['controller.services_arguments']
  #ICS\WebapiBundle\Command\:
  #resource: "../src/Command"
  #tags: ['controller.services_arguments']
  #ICS\WebapiBundle\Twig\:
  #resource: "../src/Twig"
  #tags: ['controller.services_arguments']
  #ICS\WebapiBundle\Form\:
  #resource: "../src/Form"
  #tags: ['controller.services_arguments']
